### ISSUE TITLE
[BUG]: `latex` feature intereres with `quarto` feature.

### ISSUE THREAD

**Issue by dylanrussellmd** [prulloac/devcontainer-features#43]
### Description of the bug

This issue was initially opened [here](https://github.com/rocker-org/devcontainer-features/issues/214#issue-2254704636) but closed as they deemed it an issue with the `latex` feature.

I built a simple Codespaces container with the following `devcontainer.json`:
```json
{
	"name": "Pandoc Development Container",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",

	// Features to add to the dev container. More info: https://containers.dev/features.
	"features": {
		"ghcr.io/rocker-org/devcontainer-features/quarto-cli:1": {
			"version": "latest",
			"installChromium": true
		},
		"ghcr.io/rocker-org/devcontainer-features/apt-packages:1": {
			"packages": "chromium"
		}, 
		"ghcr.io/devcontainers-contrib/features/pandoc:1": {
			"version": "latest"
		}, 
		"ghcr.io/prulloac/devcontainer-features/latex:1": {
			"scheme": "full",
			"mirror": "https://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/"
		}
	}
}
```
This failed with the following error:
```
#18 0.465 ===========================================================================
#18 0.465 Feature       : Quarto CLI
#18 0.465 Description   : Installs the Quarto CLI. Auto-detects latest version.
#18 0.465 Id            : ghcr.io/rocker-org/devcontainer-features/quarto-cli
#18 0.465 Version       : 1.1.2
#18 0.465 Documentation : ********/rocker-org/devcontainer-features/tree/main/src/quarto-cli
#18 0.465 Options       :
#18 0.465     VERSION="latest"
#18 0.465     INSTALLTINYTEX="false"
#18 0.465     INSTALLCHROMIUM="********"
#18 0.465 ===========================================================================#18 0.484 Downloading Quarto CLI...
#18 0.532 /tmp/quarto /tmp/dev-container-features/quarto-cli_3
#18 1.585 Selecting previously unselected package quarto.#18 1.608 (Reading database ... 32464 files and directories currently installed.)
#18 1.609 Preparing to unpack quarto.deb ...
#18 1.633 Unpacking quarto (1.4.553) ...
#18 7.432 Setting up quarto (1.4.553) ...
#18 7.568 /tmp/dev-container-features/quarto-cli_3
#18 7.580 Installing chromium...
#18 7.580 (!) Quarto CLI installs headless Chromium via Puppeteer. The bundled Chromium that Puppeteer installs may not work on Docker containers.
#18 7.580     Please check the Puppeteer document: ********/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker
#18 7.594 bash: line 1: quarto: command not found
#18 7.596 ERROR: Feature "Quarto CLI" (ghcr.io/rocker-org/devcontainer-features/quarto-cli) failed to install! Look at the documentation at ********/rocker-org/devcontainer-features/tree/main/src/quarto-cli for help troubleshooting this error.
#18 ERROR: process "/bin/sh -c cp -ar /tmp/build-features-src/quarto-cli_3 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/quarto-cli_3  && cd /tmp/dev-container-features/quarto-cli_3  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/quarto-cli_3" did not complete successfully: exit code: 127
------
 > [dev_containers_target_stage 8/8] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=quarto-cli_3,target=/tmp/build-features-src/quarto-cli_3     cp -ar /tmp/build-features-src/quarto-cli_3 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/quarto-cli_3  && cd /tmp/dev-container-features/quarto-cli_3  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/quarto-cli_3:
1.608 (Reading database ... 32464 files and directories currently installed.)
1.609 Preparing to unpack quarto.deb ...
1.633 Unpacking quarto (1.4.553) ...
7.432 Setting up quarto (1.4.553) ...
7.568 /tmp/dev-container-features/quarto-cli_3
7.580 Installing chromium...
7.580 (!) Quarto CLI installs headless Chromium via Puppeteer. The bundled Chromium that Puppeteer installs may not work on Docker containers.
7.580     Please check the Puppeteer document: ********/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker
7.594 bash: line 1: quarto: command not found
7.596 ERROR: Feature "Quarto CLI" (ghcr.io/rocker-org/devcontainer-features/quarto-cli) failed to install! Look at the documentation at ********/rocker-org/devcontainer-features/tree/main/src/quarto-cli for help troubleshooting this error.
------
Dockerfile.extended:51
--------------------
  50 |     
  51 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=quarto-cli_3,target=/tmp/build-features-src/quarto-cli_3 \
  52 | >>>     cp -ar /tmp/build-features-src/quarto-cli_3 /tmp/dev-container-features \
  53 | >>>  && chmod -R 0755 /tmp/dev-container-features/quarto-cli_3 \
  54 | >>>  && cd /tmp/dev-container-features/quarto-cli_3 \
  55 | >>>  && chmod +x ./devcontainer-features-install.sh \
  56 | >>>  && ./devcontainer-features-install.sh \
  57 | >>>  && rm -rf /tmp/dev-container-features/quarto-cli_3
  58 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/quarto-cli_3 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/quarto-cli_3  && cd /tmp/dev-container-features/quarto-cli_3  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/quarto-cli_3" did not complete successfully: exit code: 127
Stop: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.1-1713598698526 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pandoc-43a4e104c62be3219495884aaff9b9fb4c77f05fc457d7e11c7aeb730b3de265-features -f /tmp/devcontainercli-root/container-features/0.56.1-1713598698526/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.1-1713598698526 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pandoc-43a4e104c62be3219495884aaff9b9fb4c77f05fc457d7e11c7aeb730b3de265-features -f /tmp/devcontainercli-root/container-features/0.56.1-1713598698526/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
    at O$ (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:1253)
{"outcome":"error","message":"Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.1-1713598698526 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pandoc-43a4e104c62be3219495884aaff9b9fb4c77f05fc457d7e11c7aeb730b3de265-features -f /tmp/devcontainercli-root/container-features/0.56.1-1713598698526/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder","description":"An error occurred setting up the container."}
    at iK (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:997)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async gAA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:3660)
    at async BC (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:4775)
    at async xeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11265)
    at async UeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11006)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.1-1713598698526 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pandoc-43a4e104c62be3219495884aaff9b9fb4c77f05fc457d7e11c7aeb730b3de265-features -f /tmp/devcontainercli-root/container-features/0.56.1-1713598698526/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.
Jobs failed, exiting the agent. Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
```
When built with this `devcontainer.json`...
```json
{
	"name": "Pandoc Development Container",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",

	// Features to add to the dev container. More info: https://containers.dev/features.
	"features": {
		"ghcr.io/rocker-org/devcontainer-features/quarto-cli:1": {
			"version": "latest",
			"installChromium": true
		},
		"ghcr.io/rocker-org/devcontainer-features/apt-packages:1": {
			"packages": "chromium"
		}, 
		"ghcr.io/devcontainers-contrib/features/pandoc:1": {
			"version": "latest"
		}//, 
		//"ghcr.io/prulloac/devcontainer-features/latex:1": {
		//	"scheme": "full",
		//	"mirror": "https://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/"
		//}
	}
}
```
the build failed. The only difference is the presence of the `latex` feature. Any idea why these two are coming in to conflict in such a way that this error is produced: `#18 7.594 bash: line 1: quarto: command not found`

### Steps To Reproduce

Open a codespace with these features:
```
{
	"name": "Pandoc Development Container",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",

	// Features to add to the dev container. More info: https://containers.dev/features.
	"features": {
		"ghcr.io/rocker-org/devcontainer-features/quarto-cli:1": {
			"version": "latest",
			"installChromium": true
		},
		"ghcr.io/rocker-org/devcontainer-features/apt-packages:1": {
			"packages": "chromium"
		}, 
		"ghcr.io/devcontainers-contrib/features/pandoc:1": {
			"version": "latest"
		}, 
		"ghcr.io/prulloac/devcontainer-features/latex:1": {
			"scheme": "full",
			"mirror": "https://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/"
		}
	}
}
```

**Comment by prulloac** [comment]
@dylanrussellmd thanks for pointing out the issue, will try to replicate and investigate on possible solutions!

**Comment by prulloac** [comment]
@dylanrussellmd I've succesfully replicated the issue, will address it and let you know once fixed. In the meantime, you may use the following configuration which actually spins up and makes the features that you require available without any issue:

```json
{
	"name": "Pandoc Development Container",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",

	// Features to add to the dev container. More info: https://containers.dev/features.
	"features": {
		"ghcr.io/rocker-org/devcontainer-features/quarto-cli:1": {
			"version": "latest",
			"installChromium": true
		},
		"ghcr.io/rocker-org/devcontainer-features/apt-packages:1": {
			"packages": "chromium"
		}, 
		"ghcr.io/devcontainers-contrib/features/pandoc:1": {
			"version": "latest"
		}, 
		"ghcr.io/prulloac/devcontainer-features/latex:1": {
			"scheme": "full",
			"mirror": "https://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/"
		}
	},

	// Forces installment order. More info: https://containers.dev/implementors/features/#overrideFeatureInstallOrder.
        "overrideFeatureInstallOrder": [
            "ghcr.io/rocker-org/devcontainer-features/apt-packages:1",
            "ghcr.io/rocker-org/devcontainer-features/quarto-cli:1",
            "ghcr.io/devcontainers-contrib/features/pandoc:1",
            "ghcr.io/prulloac/devcontainer-features/latex:1"
        ]
}
```

**Comment by prulloac** [comment]
@dylanrussellmd issue solved, please feel free to test!
